### ISSUE TITLE
Comments about Remittance contract

### ISSUE THREAD

**Issue by maptuhec** [nickpanaiotov/remittance#1]
pragma solidity ^0.4.19;

import "./Killable.sol";

contract Remittance is Killable {
	//Comment: Add events to the contract
    uint private limitDuration;

    struct Transation {
        address from;
        address to;
        uint amount;
        uint deadline;
    }

    function Remittance(uint _limitDuration) public {
        require(_limitDuration > 0);

        owner = msg.sender;
        limitDuration = _limitDuration;
    }
	//Comment Typo in Transation, missed C
    mapping(bytes32 => Transation) private transactions;

	//Comment: What happens if the passwordHash is empty ?
	//Comment: What will happen if we try to submit transaction with hash that already exists?
    function submitTransation(address to, uint duration, bytes32 passwordHash) public payable returns (bool) {
        require(msg.value > 0);
        require(limitDuration > duration);

        transactions[passwordHash] = Transation({from: msg.sender, to: to, amount: msg.value, deadline: block.number + duration});

        return true;
    }
	//Comment: If one of the passwords or both are empty?
    function withdraw(string cPassword, string bPassword) public returns (bool) {
        bytes32 key = keccak256(cPassword, bPassword);
        Transation memory transation = transactions[key];

        if (msg.sender == transation.from && block.number > transation.deadline) {
            transation.from.transfer(transation.amount);
            delete(transactions[key]);

            return true;
        }

        if (msg.sender == transation.to && block.number <= transation.deadline) {
            transation.to.transfer(transation.amount);
            delete(transactions[key]);

            return true;
        }

        revert();
    }

    function getLimitDuration() public view returns (uint){
        return limitDuration;
    }

	//Comment: If one of the passwords or both are empty?
    function getDeadline(string cPassword, string bPassword) public view returns (uint) {
        bytes32 key = keccak256(cPassword, bPassword);
        Transation memory transation = transactions[key];

        return transation.deadline;
    }
}

**Comment by nickpanaiotov** [comment]
Suggested improvements are implemented and merged to master.
